### ISSUE TITLE
Out of Memory Issue When Using SQLite in a React-Vite Ionic Environment 

### ISSUE THREAD

**Issue by l1985q** [jepiqueau/react-sqlite-app-starter#39]
More and more components and frameworks are moving away from using webpack, and I started using your library for that purpose. However, I'm facing several issues while integrating the latest version of ArcGIS. I was wondering if you could help me with implementing typeorm+sqlite in an Ionic React Vite environment.

In my Ionic React Vite project, I'm using @capacitor-community/sqlite for database operations. However, when I try to execute db.open(), I encounter the following error:

Uncaught (in promise) Error: out of memory
at f2.handleError (sql-wasm.js:91:290)
at new f2 (sql-wasm.js:76:213)
at database.ts:53:24

Could you please look into this issue and provide some guidance?

```

import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import { defineCustomElements as jeepSqlite, applyPolyfills, JSX as LocalJSX  } from "jeep-sqlite/loader";
import { HTMLAttributes } from 'react';
import { Capacitor } from '@capacitor/core';
import { CapacitorSQLite, SQLiteConnection, SQLiteDBConnection } from '@capacitor-community/sqlite';

type StencilToReact<T> = {
  [P in keyof T]?: T[P] & Omit<HTMLAttributes<Element>, 'className'> & {
    class?: string;
  };
} ;

declare global {
  export namespace JSX {
    interface IntrinsicElements extends StencilToReact<LocalJSX.IntrinsicElements> {
    }
  }
}

applyPolyfills().then(() => {
  jeepSqlite(window);
});
window.addEventListener('DOMContentLoaded', async () => {
  console.log('$$$ in index $$$');
  const platform = Capacitor.getPlatform();
  const sqlite: SQLiteConnection = new SQLiteConnection(CapacitorSQLite)
  try {
    if(platform === "web") {
      const jeepEl = document.createElement("jeep-sqlite");
      document.body.appendChild(jeepEl);
      await customElements.whenDefined('jeep-sqlite');
      await sqlite.initWebStore();
    }
    const ret = await sqlite.checkConnectionsConsistency();
    const isConn = (await sqlite.isConnection("db_issue9", false)).result;
    var db: SQLiteDBConnection
    if (ret.result && isConn) {
      db = await sqlite.retrieveConnection("db_issue9", false);
    } else {
      db = await sqlite.createConnection("db_issue9", false, "no-encryption", 1, false);
    }

    await db.open();
    let query = `
    CREATE TABLE IF NOT EXISTS test (
      id INTEGER PRIMARY KEY NOT NULL,
      name TEXT NOT NULL
    );
    `

    const res: any = await db.execute(query);
    console.log(`res: ${JSON.stringify(res)}`);
    await db.close();
    await sqlite.closeConnection("db_issue9", false);
    const container = document.getElementById('root');
    const root = createRoot(container!);
    root.render(
      <React.StrictMode>
        <App />
      </React.StrictMode>
    );
  } catch (err) {
    console.log(`Error: ${err}`);
    throw new Error(`Error: ${err}`)
  }
});
```

**Comment by jepiqueau** [comment]
@l1985q can you share your package.json. Did you copy the sql-wasm.wasm file from node_modules/sql.js  into the public/assets folder of your app?

**Comment by l1985q** [comment]
> @l1985q can you share your package.json. Did you copy the sql-wasm.wasm file from node_modules/sql.js into the public/assets folder of your app?
```

{
  "name": "tree-tracker-app",
  "private": true,
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "dev": "npm run copysqlwasm && vite",
    "build": "npm run copysqlwasm && tsc && vite build",
    "preview": "vite preview",
    "test.e2e": "cypress run",
    "test.unit": "vitest",
    "lint": "eslint",
    "copysqlwasm": "copyfiles -u 3 node_modules/sql.js/dist/sql-wasm.wasm public/assets"
  },
  "dependencies": {
    "@capacitor/app": "5.0.6",
    "@capacitor/core": "5.5.1",
    "@capacitor/haptics": "5.0.6",
    "@capacitor/keyboard": "5.0.6",
    "@capacitor/status-bar": "5.0.6",
    "@ionic/react": "^7.0.0",
    "@ionic/react-router": "^7.0.0",
    "@types/react-router": "^5.1.20",
    "@types/react-router-dom": "^5.3.3",
    "ionicons": "^7.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router": "^5.3.4",
    "react-router-dom": "^5.3.4"
  },
  "devDependencies": {
    "@capacitor-community/sqlite": "^5.4.2-2",
    "@capacitor/cli": "5.5.1",
    "@testing-library/dom": ">=7.21.4",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^14.4.3",
    "@types/react": "^18.0.27",
    "@types/react-dom": "^18.0.10",
    "@vitejs/plugin-legacy": "^5.0.0",
    "@vitejs/plugin-react": "^4.0.1",
    "copyfiles": "^2.4.1",
    "cypress": "^13.5.0",
    "eslint": "^8.35.0",
    "eslint-plugin-react": "^7.32.2",
    "jeep-sqlite": "^2.5.4",
    "jsdom": "^22.1.0",
    "react-sqlite-hook": "^3.2.1",
    "terser": "^5.4.0",
    "typescript": "^5.1.6",
    "vite": "^5.0.0",
    "vitest": "^0.34.6"
  },
  "description": "An Ionic project"
}

```

**Comment by jepiqueau** [comment]
@l1985q with Vite you must use 
```ts
import { Capacitor } from '@capacitor/core';
import { JeepSqlite } from 'jeep-sqlite/dist/components/jeep-sqlite';
import { defineCustomElements as pwaElements} from '@ionic/pwa-elements/loader';

pwaElements(window);
customElements.define('jeep-sqlite', JeepSqlite);
const platform = Capacitor.getPlatform();

```
look at [ionic7-react-sqlite-app](https://github.com/jepiqueau/blog-tutorials-apps/tree/main/SQLite/Part-1/ionic7-react-sqlite-app) and [jeep-tutorials](https://jepiqueau.github.io/)
i am in a process to write tutorials so all the other applications on my site are deprecated and will be remove as it is a tremendous work to maintain all of them in view of the quick development of capacitor, Ionic and others frameworks. thanks for your understanding

**Comment by l1985q** [comment]
> @l1985q can you share your package.json. Did you copy the sql-wasm.wasm file from node_modules/sql.js into the public/assets folder of your app?

OK, I'll test it right away.
If the test is successful, I would like to use typeorm, any suggestions?Thanks

**Comment by jepiqueau** [comment]
@l1985q Look at [capacitor-sqlite-react-typeorm-app](https://github.com/cosentino/capacitor-sqlite-react-typeorm-app/)
